package br.com.farmaware.view;

import br.com.farmaware.model.User;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author lucasdm
 * @author michelenathalie
 */
public class ManagerView extends javax.swing.JFrame {
    private User currentUser = null;
    private JFrame parent = null;
    private boolean isCashierOpen = false;
    /**
     * Creates new form ManagerView
     */
    public ManagerView(User currentUser, JFrame parent) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.currentUser = currentUser;
        this.parent = parent;
        
        if(currentUser != null){
            lblUsername.setText("Olá, " + currentUser.getName().split(" ")[0] + ".");
        }
        else{
            JOptionPane.showMessageDialog(this, "Houve um problema ao iniciar a sessão! Tente novamente!", "Erro", 0);
            logout();
            return;
        }
        
        if (currentUser.getCateg() == User.CLERK_TYPE){
            pnlBtnUsers.setEnabled(false);
            pnlBtnUsers.setBackground(Color.LIGHT_GRAY);
            pnlBtnSales.setEnabled(false);
            pnlBtnSales.setBackground(Color.LIGHT_GRAY);
            pnlBtnProducts.setEnabled(false);
            pnlBtnProducts.setBackground(Color.LIGHT_GRAY);
            pnlBtnDrugs.setEnabled(false);
            pnlBtnDrugs.setBackground(Color.LIGHT_GRAY);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainWrapper = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlBtnSell = new javax.swing.JPanel();
        lblIcon5 = new javax.swing.JLabel();
        lblText5 = new javax.swing.JLabel();
        pnlBtnCashier = new javax.swing.JPanel();
        lblIcon2 = new javax.swing.JLabel();
        lblText2 = new javax.swing.JLabel();
        pnlBtnUsers = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        pnlBtnClients = new javax.swing.JPanel();
        lblIcon1 = new javax.swing.JLabel();
        lblText1 = new javax.swing.JLabel();
        pnlBtnSales = new javax.swing.JPanel();
        lblIcon3 = new javax.swing.JLabel();
        lblText3 = new javax.swing.JLabel();
        pnlBtnDrugs = new javax.swing.JPanel();
        lblIcon4 = new javax.swing.JLabel();
        lblText4 = new javax.swing.JLabel();
        pnlBtnProducts = new javax.swing.JPanel();
        lblIcon6 = new javax.swing.JLabel();
        lblText6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mainWrapper.setBackground(new java.awt.Color(255, 255, 255));

        lblUsername.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(102, 102, 102));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsername.setText("Olá, <username>.");

        jLabel2.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>Farma<b>Ware</b></html>");

        pnlBtnSell.setBackground(new java.awt.Color(255, 255, 255));
        pnlBtnSell.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBtnSell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBtnSellMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBtnUsersMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBtnUsersMouseEntered(evt);
            }
        });

        lblIcon5.setBackground(new java.awt.Color(255, 255, 255));
        lblIcon5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/farmaware/view/sell.png"))); // NOI18N
        pnlBtnSell.add(lblIcon5);

        lblText5.setBackground(new java.awt.Color(255, 255, 255));
        lblText5.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblText5.setForeground(new java.awt.Color(102, 102, 102));
        lblText5.setText("Vender");
        pnlBtnSell.add(lblText5);

        pnlBtnCashier.setBackground(new java.awt.Color(255, 255, 255));
        pnlBtnCashier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBtnCashier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBtnCashierMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBtnUsersMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBtnUsersMouseEntered(evt);
            }
        });

        lblIcon2.setBackground(new java.awt.Color(255, 255, 255));
        lblIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/farmaware/view/cashier.png"))); // NOI18N
        pnlBtnCashier.add(lblIcon2);

        lblText2.setBackground(new java.awt.Color(255, 255, 255));
        lblText2.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblText2.setForeground(new java.awt.Color(102, 102, 102));
        lblText2.setText("Fechado");
        pnlBtnCashier.add(lblText2);

        pnlBtnUsers.setBackground(new java.awt.Color(255, 255, 255));
        pnlBtnUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBtnUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBtnUsersMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBtnUsersMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBtnUsersMouseEntered(evt);
            }
        });

        lblIcon.setBackground(new java.awt.Color(255, 255, 255));
        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/farmaware/view/employee.png"))); // NOI18N
        pnlBtnUsers.add(lblIcon);

        lblText.setBackground(new java.awt.Color(255, 255, 255));
        lblText.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblText.setForeground(new java.awt.Color(102, 102, 102));
        lblText.setText("Usuários");
        pnlBtnUsers.add(lblText);

        pnlBtnClients.setBackground(new java.awt.Color(255, 255, 255));
        pnlBtnClients.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBtnClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBtnClientsMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBtnUsersMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBtnUsersMouseEntered(evt);
            }
        });

        lblIcon1.setBackground(new java.awt.Color(255, 255, 255));
        lblIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/farmaware/view/customer_icon.png"))); // NOI18N
        pnlBtnClients.add(lblIcon1);

        lblText1.setBackground(new java.awt.Color(255, 255, 255));
        lblText1.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblText1.setForeground(new java.awt.Color(102, 102, 102));
        lblText1.setText("Clientes");
        pnlBtnClients.add(lblText1);

        pnlBtnSales.setBackground(new java.awt.Color(255, 255, 255));
        pnlBtnSales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBtnSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBtnSalesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBtnUsersMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBtnUsersMouseEntered(evt);
            }
        });

        lblIcon3.setBackground(new java.awt.Color(255, 255, 255));
        lblIcon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/farmaware/view/cart.png"))); // NOI18N
        pnlBtnSales.add(lblIcon3);

        lblText3.setBackground(new java.awt.Color(255, 255, 255));
        lblText3.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblText3.setForeground(new java.awt.Color(102, 102, 102));
        lblText3.setText("Vendas");
        pnlBtnSales.add(lblText3);

        pnlBtnDrugs.setBackground(new java.awt.Color(255, 255, 255));
        pnlBtnDrugs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBtnDrugs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBtnDrugsMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBtnUsersMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBtnUsersMouseEntered(evt);
            }
        });

        lblIcon4.setBackground(new java.awt.Color(255, 255, 255));
        lblIcon4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/farmaware/view/pill_bottle.png"))); // NOI18N
        pnlBtnDrugs.add(lblIcon4);

        lblText4.setBackground(new java.awt.Color(255, 255, 255));
        lblText4.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblText4.setForeground(new java.awt.Color(102, 102, 102));
        lblText4.setText("Medic.");
        pnlBtnDrugs.add(lblText4);

        pnlBtnProducts.setBackground(new java.awt.Color(255, 255, 255));
        pnlBtnProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBtnProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBtnProductsMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBtnUsersMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBtnUsersMouseEntered(evt);
            }
        });

        lblIcon6.setBackground(new java.awt.Color(255, 255, 255));
        lblIcon6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/farmaware/view/box.png"))); // NOI18N
        pnlBtnProducts.add(lblIcon6);

        lblText6.setBackground(new java.awt.Color(255, 255, 255));
        lblText6.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblText6.setForeground(new java.awt.Color(102, 102, 102));
        lblText6.setText("Produtos");
        pnlBtnProducts.add(lblText6);

        javax.swing.GroupLayout mainWrapperLayout = new javax.swing.GroupLayout(mainWrapper);
        mainWrapper.setLayout(mainWrapperLayout);
        mainWrapperLayout.setHorizontalGroup(
            mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2)
            .addGroup(mainWrapperLayout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(mainWrapperLayout.createSequentialGroup()
                        .addComponent(pnlBtnSales, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(pnlBtnDrugs, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(pnlBtnProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainWrapperLayout.createSequentialGroup()
                        .addComponent(pnlBtnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(pnlBtnClients, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)))
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(mainWrapperLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlBtnSell, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pnlBtnCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        mainWrapperLayout.setVerticalGroup(
            mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainWrapperLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblUsername)
                .addGap(30, 30, 30)
                .addGroup(mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBtnSell, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlBtnCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBtnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlBtnClients, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 9, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addGroup(mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pnlBtnSales, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnlBtnDrugs, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlBtnProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        btnLogout.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(102, 102, 102));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/farmaware/view/off.png"))); // NOI18N
        btnLogout.setText("Encerrar Sessão");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        logout();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void pnlBtnUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnUsersMouseEntered
        changePnlBtnColor(true, (JPanel)evt.getComponent());
    }//GEN-LAST:event_pnlBtnUsersMouseEntered

    private void pnlBtnUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnUsersMouseExited
        changePnlBtnColor(false, (JPanel)evt.getComponent());
    }//GEN-LAST:event_pnlBtnUsersMouseExited

    private void pnlBtnSellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnSellMouseClicked
        if(!isCashierOpen)
            return;
        
        SaleView sv = new SaleView(currentUser);
        sv.setVisible(true);
    }//GEN-LAST:event_pnlBtnSellMouseClicked

    private void pnlBtnCashierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnCashierMouseClicked
        if(isCashierOpen){
            // If it is a clerk, ask for authentication before opening the cashier
            if(currentUser.getCateg() == 1){
                AuthView av = new AuthView();
                av.setModal(true);
                av.setVisible(true);
                boolean isAuthenticated = av.getAuth();
                av.dispose();

                if (!isAuthenticated)
                    return;
            }
        }
        
        isCashierOpen = !isCashierOpen;
        pnlBtnSell.setEnabled(isCashierOpen);
        lblText2.setText((isCashierOpen ? "Aberto" : "Fechado"));
    }//GEN-LAST:event_pnlBtnCashierMouseClicked

    private void pnlBtnUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnUsersMouseClicked
        if(!pnlBtnUsers.isEnabled())
            return;
        
        RecordView rv = new RecordView(RecordView.USERS);
        rv.setVisible(true);
    }//GEN-LAST:event_pnlBtnUsersMouseClicked

    private void pnlBtnClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnClientsMouseClicked
        RecordView rv = new RecordView(RecordView.CLIENTS);
        rv.setVisible(true);
    }//GEN-LAST:event_pnlBtnClientsMouseClicked

    private void pnlBtnSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnSalesMouseClicked
        if(!pnlBtnSales.isEnabled())
            return;
        
        RecordView rv = new RecordView(RecordView.SALES);
        rv.setVisible(true);
    }//GEN-LAST:event_pnlBtnSalesMouseClicked

    private void pnlBtnDrugsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnDrugsMouseClicked
        if(!pnlBtnDrugs.isEnabled())
            return;
        
        RecordView rv = new RecordView(RecordView.DRUGS);
        rv.setVisible(true);
    }//GEN-LAST:event_pnlBtnDrugsMouseClicked

    private void pnlBtnProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBtnProductsMouseClicked
        if(!pnlBtnProducts.isEnabled())
            return;
        
        RecordView rv = new RecordView(RecordView.PRODUCTS);
        rv.setVisible(true);
    }//GEN-LAST:event_pnlBtnProductsMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        logout();
    }//GEN-LAST:event_formWindowClosing
    
    private void changePnlBtnColor(boolean isOver, JPanel panel){
        if(!panel.isEnabled())
            return;
        panel.setBackground((isOver ? Color.lightGray : Color.WHITE));
    }
    
    private void logout(){
        this.isCashierOpen = false;
        this.dispose();
        ((LoginView)parent).clearFields();
        parent.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerView(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblIcon1;
    private javax.swing.JLabel lblIcon2;
    private javax.swing.JLabel lblIcon3;
    private javax.swing.JLabel lblIcon4;
    private javax.swing.JLabel lblIcon5;
    private javax.swing.JLabel lblIcon6;
    private javax.swing.JLabel lblText;
    private javax.swing.JLabel lblText1;
    private javax.swing.JLabel lblText2;
    private javax.swing.JLabel lblText3;
    private javax.swing.JLabel lblText4;
    private javax.swing.JLabel lblText5;
    private javax.swing.JLabel lblText6;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel mainWrapper;
    private javax.swing.JPanel pnlBtnCashier;
    private javax.swing.JPanel pnlBtnClients;
    private javax.swing.JPanel pnlBtnDrugs;
    private javax.swing.JPanel pnlBtnProducts;
    private javax.swing.JPanel pnlBtnSales;
    private javax.swing.JPanel pnlBtnSell;
    private javax.swing.JPanel pnlBtnUsers;
    // End of variables declaration//GEN-END:variables
}
