package br.com.farmaware.view;

import br.com.farmaware.dao.ClientDAO;
import br.com.farmaware.dao.SaleDAO;
import br.com.farmaware.model.Client;
import br.com.farmaware.model.Sale;
import br.com.farmaware.model.Saleable;
import br.com.farmaware.model.Sold;
import br.com.farmaware.model.User;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucasdm
 */
public class SaleView extends javax.swing.JFrame {
    // Payment types constants
    private static final int MONEY = 0;
    private static final int CREDIT_CARD = 1;
    private static final int DEBIT_CARD = 2;
    private static final int OTHER = 3;
    
    Sale sale = null;
    
    DefaultTableModel tableModel;
    
    private double totalProdPrice = 0d;
    private double discount = 0d;
    private double totalPrice = 0d;
    private Client client;
    private User seller;
    
    /**
     * Creates new form LoginView
     */
    public SaleView(User currentUser) {
        initComponents();
        this.tableModel = (DefaultTableModel)tblSolds.getModel();
        this.setLocationRelativeTo(null);
        this.seller = currentUser;
        cbPayment.setSelectedIndex(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainWrapper = new javax.swing.JPanel();
        lblAction = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtClientCpf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lbl_farmaware9 = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        cbPayment = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnAddProduct = new javax.swing.JButton();
        btnChooseClient = new javax.swing.JButton();
        lblProductPrice = new javax.swing.JLabel();
        lblDiscountValue = new javax.swing.JLabel();
        lbl_farmaware12 = new javax.swing.JLabel();
        lblDiscount = new javax.swing.JLabel();
        lbl_farmaware14 = new javax.swing.JLabel();
        lbl_farmaware15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSolds = new javax.swing.JTable();
        btnRemoveProduct = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        mainWrapper.setBackground(new java.awt.Color(255, 255, 255));

        lblAction.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        lblAction.setForeground(new java.awt.Color(102, 102, 102));
        lblAction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAction.setText("Cadastrar Venda");

        jLabel2.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html>Farma<b>Ware</b></html>");

        jLabel3.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Produtos:");

        txtClientCpf.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        txtClientCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClientCpfFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("CPF Cliente:");

        lbl_farmaware9.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lbl_farmaware9.setForeground(new java.awt.Color(102, 102, 102));
        lbl_farmaware9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lbl_farmaware9.setText("<html><b>Total:</b>"); // NOI18N
        lbl_farmaware9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblTotalPrice.setFont(new java.awt.Font("Helvetica", 1, 36)); // NOI18N
        lblTotalPrice.setForeground(new java.awt.Color(102, 102, 102));
        lblTotalPrice.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTotalPrice.setText("R$ 0,00"); // NOI18N
        lblTotalPrice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cbPayment.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        cbPayment.setForeground(new java.awt.Color(102, 102, 102));
        cbPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão de Crédito", "Cartão de Débito", "Outro" }));
        cbPayment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbPayment.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cbPaymentFocusLost(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setText("Método de pagamento:");

        btnAddProduct.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        btnAddProduct.setForeground(new java.awt.Color(102, 102, 102));
        btnAddProduct.setText("Adicionar Produto");
        btnAddProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductActionPerformed(evt);
            }
        });

        btnChooseClient.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnChooseClient.setText("...");
        btnChooseClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChooseClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseClientActionPerformed(evt);
            }
        });

        lblProductPrice.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblProductPrice.setForeground(new java.awt.Color(102, 102, 102));
        lblProductPrice.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblProductPrice.setText("0,00"); // NOI18N
        lblProductPrice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblDiscountValue.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lblDiscountValue.setForeground(new java.awt.Color(102, 102, 102));
        lblDiscountValue.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblDiscountValue.setText("0,00"); // NOI18N
        lblDiscountValue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_farmaware12.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lbl_farmaware12.setForeground(new java.awt.Color(102, 102, 102));
        lbl_farmaware12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_farmaware12.setText("Produto(s):"); // NOI18N
        lbl_farmaware12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblDiscount.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        lblDiscount.setForeground(new java.awt.Color(102, 102, 102));
        lblDiscount.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDiscount.setText("Desconto (5%):"); // NOI18N
        lblDiscount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_farmaware14.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lbl_farmaware14.setForeground(new java.awt.Color(102, 102, 102));
        lbl_farmaware14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_farmaware14.setText("R$"); // NOI18N
        lbl_farmaware14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbl_farmaware15.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        lbl_farmaware15.setForeground(new java.awt.Color(102, 102, 102));
        lbl_farmaware15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_farmaware15.setText("R$"); // NOI18N
        lbl_farmaware15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        tblSolds.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        tblSolds.setForeground(new java.awt.Color(51, 51, 51));
        tblSolds.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Preço", "Qtd"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSolds.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane2.setViewportView(tblSolds);

        btnRemoveProduct.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        btnRemoveProduct.setForeground(new java.awt.Color(102, 102, 102));
        btnRemoveProduct.setText("Remover Produto");
        btnRemoveProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemoveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainWrapperLayout = new javax.swing.GroupLayout(mainWrapper);
        mainWrapper.setLayout(mainWrapperLayout);
        mainWrapperLayout.setHorizontalGroup(
            mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainWrapperLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainWrapperLayout.createSequentialGroup()
                        .addComponent(btnRemoveProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainWrapperLayout.createSequentialGroup()
                        .addComponent(txtClientCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChooseClient, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblTotalPrice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_farmaware9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(cbPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(mainWrapperLayout.createSequentialGroup()
                            .addGroup(mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblDiscount, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                .addComponent(lbl_farmaware12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_farmaware14)
                                .addComponent(lbl_farmaware15))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDiscountValue, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblProductPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20))
        );
        mainWrapperLayout.setVerticalGroup(
            mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainWrapperLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainWrapperLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblAction)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainWrapperLayout.createSequentialGroup()
                        .addGroup(mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClientCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChooseClient, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(mainWrapperLayout.createSequentialGroup()
                                .addComponent(lblProductPrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDiscountValue))
                            .addGroup(mainWrapperLayout.createSequentialGroup()
                                .addGroup(mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_farmaware12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl_farmaware15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDiscount)
                                    .addComponent(lbl_farmaware14))))
                        .addGap(35, 35, 35)
                        .addComponent(lbl_farmaware9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainWrapperLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblTotalPrice))
                    .addGroup(mainWrapperLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRemoveProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnRegister.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(102, 102, 102));
        btnRegister.setText("Cadastrar");
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Helvetica", 1, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(102, 102, 102));
        btnCancel.setText("Cancelar");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainWrapper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainWrapper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // Get payment
        int paymentMethod = cbPayment.getSelectedIndex();
        
        // Get client and validate cpf
        String cpf = txtClientCpf.getText();
        if(cpf.equals("") || !cpf.matches("^[0-9]{11}$")){
            JOptionPane.showMessageDialog(this, "Insira um CPF válido!", "Atenção", 0);
            return;
        }
        client = new Client(cpf);
        ClientDAO dao = new ClientDAO();
        try {
            client = dao.search(client);
            
            if(client == null){
                JOptionPane.showMessageDialog(this, "Este CPF não está registrado!", "Erro", 0);
                return;
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro de SQL: \n" + ex.getMessage(), "Erro", 0);
            return;
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Erro de Classe: \n" + ex.getMessage(), "Erro", 0);
            return;
        }
        
        // Write
        boolean success = false;
        SaleDAO sDao = new SaleDAO();
        
        //Get sold list
        List<Sold> solds = null;
        for (int i = 0; i < tableModel.getRowCount(); i++){
            int saleableId = Integer.parseInt((String)tableModel.getValueAt(i, 0));
            int qty = Integer.parseInt((String)tableModel.getValueAt(i, 3));
            Sold sold = new Sold(saleableId, 0, qty);
            solds.add(sold);
        }
        
        Sale currentSale = new Sale(solds, client.getCpf(), seller.getCpf(), totalPrice);
        
        try {
            success = sDao.insert(currentSale);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro de SQL: \n" + ex.getMessage(), "Erro", 0);
            return;
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Erro de Classe: \n" + ex.getMessage(), "Erro", 0);
            return;
        }
        
        if(success){
            JOptionPane.showMessageDialog(this, (sale == null ? "Gravado" : "Alterado") + " com sucesso!", "Sucesso", 1);
            this.dispose();
        }
        else
            JOptionPane.showMessageDialog(this, "Erro ao " + (sale == null ? "gravar" : "alterar") + "! Tente novamente!", "Erro", 0);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtClientCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClientCpfFocusLost
        updatePrice();
    }//GEN-LAST:event_txtClientCpfFocusLost

    private void cbPaymentFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbPaymentFocusLost
        updatePrice();
    }//GEN-LAST:event_cbPaymentFocusLost

    private void btnChooseClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseClientActionPerformed
        ChooserView cv = new ChooserView(ChooserView.CLIENT);
        cv.setModal(true);
        cv.setVisible(true);
        
        Client client = (Client)cv.getSelectedEntity();
        
        if(client != null){
            txtClientCpf.setText(client.getCpf());
            this.client = client;
            updatePrice();
        }
        else
            JOptionPane.showMessageDialog(this, "Nenhum cliente selecionado!", "Erro", 0);
    }//GEN-LAST:event_btnChooseClientActionPerformed

    private void btnAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductActionPerformed
        ChooserView cv = new ChooserView(ChooserView.PRODUCT);
        cv.setModal(true);
        cv.setVisible(true);
        Saleable saleable = (Saleable)cv.getSelectedEntity();
        
        for (int i = 0; i < tableModel.getRowCount(); i++){
            if (saleable.getId() == Integer.parseInt((String)tableModel.getValueAt(i, 0))){
                JOptionPane.showMessageDialog(this, "Produto já adicionado à lista!", "Atenção", 0);
                return;
            }
        }
        
        if(saleable != null){
            Object[] values = new Object[]{saleable.getName(), saleable.getPrice(), 1};
            tableModel.addRow(values);
        }
        
        updatePrice();
    }//GEN-LAST:event_btnAddProductActionPerformed

    private void btnRemoveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveProductActionPerformed
        if(tblSolds.getSelectedRow() < 0){
            JOptionPane.showMessageDialog(this, "Selecione um registro!", "Atenção", 0);
            return;
        }
        
        tableModel.removeRow(tblSolds.getSelectedRow());
        
        updatePrice();
    }//GEN-LAST:event_btnRemoveProductActionPerformed

    private void updatePrice(){
        Locale brLocale = new Locale( "pt", "BR" );  
        NumberFormat realFormat = NumberFormat.getCurrencyInstance(brLocale); 
        
        // Total product prices
        totalProdPrice = 0d;
        for (int i = 0; i < tableModel.getRowCount(); i++){
            double prodPrice = Double.parseDouble((String)tableModel.getValueAt(i, 2));
            int qtd = Integer.parseInt((String)tableModel.getValueAt(i, 3));
            totalProdPrice += prodPrice * qtd;
        }
        lblProductPrice.setText(realFormat.format(totalProdPrice));
        
        // Discount
        discount = 0d;
        if(client != null){
            int paymentMethod = cbPayment.getSelectedIndex();
            if(client.getCateg() == Client.MANAGER){
                if(paymentMethod == MONEY)
                    discount = 0.05;
            }
            else if(client.getCateg() == Client.CLERK)
                discount = 0.2;
        }
        
        double priceOff = totalProdPrice * discount;
        
        lblDiscount.setText("Desconto (" + String.valueOf(discount * 100) + "%): ");
        lblDiscountValue.setText(realFormat.format(priceOff));
        
        // Total price
        totalPrice = totalProdPrice - priceOff;
        lblTotalPrice.setText(realFormat.format(totalPrice));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaleView(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProduct;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChooseClient;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnRemoveProduct;
    private javax.swing.JComboBox<String> cbPayment;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAction;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblDiscountValue;
    private javax.swing.JLabel lblProductPrice;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JLabel lbl_farmaware12;
    private javax.swing.JLabel lbl_farmaware14;
    private javax.swing.JLabel lbl_farmaware15;
    private javax.swing.JLabel lbl_farmaware9;
    private javax.swing.JPanel mainWrapper;
    private javax.swing.JTable tblSolds;
    private javax.swing.JTextField txtClientCpf;
    // End of variables declaration//GEN-END:variables
}
